Vancelot/inspec migration
osuosl-cookbooks/dobc pull request #6
Opened 2019-04-19 18:29 UTC by Vancelot11

Converge and verifies successfully.

2019-04-19 18:31 UTC, Vancelot11 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Migrate from ServerSpec to InSpec](https://trello.com/c/2EA1WbBL/1082-migrate-from-serverspec-to-inspec)

2019-04-19 23:13 UTC, ramereth requested changes
You also need to remove the old ServerSpec tests.

2019-04-19 23:13 UTC, ramereth commented on test/integration/default/inspec/default_test.rb
> +describe command('docker ps --format "{{.Names}}:{{.Status}}"') do
Please change this to the ``docker_container`` resource.

2019-04-19 23:13 UTC, ramereth commented on test/integration/default/inspec/default_test.rb
> +describe command('docker ps --format "{{.Names}}:{{.Status}}"') do
Please change this to the ``docker_container`` resource.

2019-04-19 23:13 UTC, ramereth commented on test/integration/default/inspec/default_test.rb
> +describe command('docker ps --format "{{.Names}}:{{.Status}}"') do
Please change this to the ``docker_container`` resource.

2019-04-24 15:58 UTC, ramereth approved these changes
Great work! Since you changed one of the files, please do a patch bump by doing ``!bump patch ~``.

2019-04-24 21:58 UTC, Vancelot11 commented
!bump patch ~

2019-04-24 21:58 UTC, merged

2019-04-24 21:59 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v2.0.1.  Have a nice day!